### ISSUE TITLE
证书申请不成功。

### ISSUE THREAD

**Issue by liang-x-j** [earlSagrada/action-aria2-script#1]
不知道为什么证书申请不成功，一个付费域名一个免费域名。
ar 12 14:50:50 ichaogu-buzz-900534 caddy[8398]: HOME=/var/lib/caddy
Mar 12 14:50:50 ichaogu-buzz-900534 caddy[8398]: LOGNAME=caddy
Mar 12 14:50:50 ichaogu-buzz-900534 caddy[8398]: USER=caddy
Mar 12 14:50:50 ichaogu-buzz-900534 caddy[8398]: INVOCATION_ID=ab18fcfc9201475fb66b8f1e7fc93f92
Mar 12 14:50:50 ichaogu-buzz-900534 caddy[8398]: JOURNAL_STREAM=8:185265
Mar 12 14:50:50 ichaogu-buzz-900534 caddy[8398]: {"level":"info","ts":1647096650.3384798,"msg":"using provided configuration","config_file":"/e>
Mar 12 14:50:50 ichaogu-buzz-900534 caddy[8398]: run: loading initial config: loading new config: starting caddy administration endpoint: liste>
Mar 12 14:50:50 ichaogu-buzz-900534 systemd[1]: Started Caddy.
Mar 12 14:50:50 ichaogu-buzz-900534 systemd[1]: caddy.service: Main process exited, code=exited, status=1/FAILURE
Mar 12 14:50:50 ichaogu-buzz-900534 systemd[1]: caddy.service: Failed with result 'exit-code'.

**Comment by earlSagrada** [comment]
您好，之前忘了在readme里面写了...

您在拥有域名之后需要再给域名添加一个“file”的子域名。所以最后您是通过"file.您的域名“来访问File Browser的。而访问AriaNg只需要使用您的域名就可以了。:)
